name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fez6k/github-profile-summary-cards@v0.6.1
        with:
          USERNAME: polcaronet
          BRANCH_NAME: main
          UTC_OFFSET: -3
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
